server:
  port: 8080

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9093
      auto-offset-reset: earliest
      auto-commit-interval: 1000
      enable-auto-commit: true
    producer:
      bootstrap-servers: localhost:9093
  datasource:
    url: jdbc:mysql://localhost:3306/TEST_DOMAIN?profileSQL=true&logger=Slf4JLogger&useSSL=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&maxQuerySizeToLog=999999
    username: root
    password: 1234
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 300000
  jpa:
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comments: true
  batch:
    jdbc:
      initialize-schema: ALWAYS