spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9093
    producer:
      bootstrap-servers: localhost:9093
  datasource:
    url: jdbc:mysql://localhost:3306/TEST_DOMAIN?rewriteBatchedStatements=true
    username: root
    password: 1234
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
  batch:
    jdbc:
      initialize-schema: ALWAYS

logging:
  level:
    org.hibernate: error
server:
  port: 0