scrape_configs:
  - job_name: "java_application"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ "localhost:8081" ]
  - job_name: system
    static_configs:
    - targets:
      - localhost
      labels:
        job: varlogs
        __path__: /monitoring/log/*.log

  - job_name: redis
    static_configs:
      - targets: ['host.docker.internal:9121']