server:
  port: 8081

spring:
  application:
    name: dr--r--r--
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      time-to-live: 3600 # 데이터 유지 시간(sec) 1시간
      host: localhost
      port: 6379
  kafka:
    consumer:
      bootstrap-servers: localhost:9093
      auto-offset-reset: earliest
      enable-auto-commit: false
      auto-commit-interval: 10
    producer:
      bootstrap-servers: localhost:9093
    backoff:
      interval: 1000
      max_failure: 3

  docker:
    compose:
      file: classpath:docker/docker-compose.yaml
      #서버가 켜지면 컨테이너들이 켜지고 꺼지면 알아서 꺼지나 필요할 때만 주석 제거
      lifecycle-management: start_only
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      #애플리케이션 로딩 시점에 다 드랍하고 다시 생성
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
        # show_sql: true
        format_sql: true
        use_sql_comments: true
  batch:
    jdbc:
      initialize-schema: ALWAYS
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: classpath:security-storage-api/social/github/github.key
            client-secret: classpath:security-storage-api/social/github/github.pub
            redirect-uri: http://localhost:8081/
          kakao:
            client-id: classpath:security-storage-api/social/kakao/client_id.key
            redirect-uri: http://localhost:8081/
            client-authentication-method: POST
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
kakao:
  private.key: classpath:security-storage-api/social/kakao/client_id.key

jwt:
  private.key: classpath:security-storage-api/jwt/jwt.key
  public.key: classpath:security-storage-api/jwt/jwt.pub
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    distribution:
      percentiles-histogram:
        all: true


  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
      tracing:
        endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0
opentracing:
  jaeger:
    service-name: dr--r--r-- # jaeger service name
    udp-sender:
      host: localhost # jaeger server ip
      port: 6831           # jaeger udp port
    enabled: true
    log-spans: true
#logging:
#  level:
#    web: debug
global:
  variable:
    front:
      local:
        domain: http://localhost:5173