server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch_sample?rewriteBatchedStatements=true
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 300000
  jpa:
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comments: true
  batch:
    jdbc:
      initialize-schema: ALWAYS